# overleaf_cv.py
import os
from pathlib import Path
import re
import sys

import requests

# Base directory of this project
PROJECT_ROOT = Path(__file__).resolve().parent

# Load .env file automatically
try:
    from dotenv import load_dotenv
    load_dotenv(PROJECT_ROOT / ".env")
except ImportError:
    pass

# Fallback parser if python-dotenv is not installed
env_path = PROJECT_ROOT / ".env"
if env_path.exists():
    with open(env_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, val = line.split("=", 1)
                os.environ.setdefault(key.strip(), val.strip().strip("'\""))

HOST = "https://www.overleaf.com"
_cached_api = None


def get_api(session_cookie: str = None):
    """Lazily initializes and returns an authenticated pyoverleaf API instance."""
    global _cached_api
    import pyoverleaf

    cookie = session_cookie or os.environ.get("OVERLEAF_SESSION")
    if not cookie:
        raise ValueError(
            "OVERLEAF_SESSION is missing. Please set it in your .env file or environment."
        )

    if _cached_api is None or session_cookie is not None:
        api = pyoverleaf.Api()
        api.login_from_cookies({"overleaf_session2": cookie})
        if session_cookie is None:
            _cached_api = api
        return api

    return _cached_api


def extract_latex(text: str) -> str:
    """Extract clean LaTeX string, handling markdown fences or surrounding conversation if generated by an LLM."""
    text = text.strip()

    # If the text contains \documentclass ... \end{document}, extract that exact block
    doc_match = re.search(r"(\\documentclass[\s\S]*?\\end\{document\})", text)
    if doc_match:
        return doc_match.group(1).strip()

    # If wrapped in markdown code blocks (```latex ... ``` or ```tex ... ``` or ``` ... ```)
    if "```" in text:
        block_match = re.search(r"```(?:latex|tex)?\s*([\s\S]*?)\s*```", text, re.IGNORECASE)
        if block_match:
            return block_match.group(1).strip()

    return text


def upload_tex(project_id: str, content: str, name: str = "main.tex", api=None):
    """Uploads LaTeX content to the Overleaf project. Accepts either a file path or raw LaTeX string."""
    api = api or get_api()

    # Check if content is a file path on disk
    if "\n" not in content and len(content) < 500 and os.path.isfile(content):
        with open(content, "r", encoding="utf-8") as f:
            raw_content = f.read()
    else:
        raw_content = content

    cleaned_content = extract_latex(raw_content)
    root = api.project_get_files(project_id)
    api.project_upload_file(project_id, root.id, name, cleaned_content.encode("utf-8"))


def compile_project(project_id: str, api=None) -> dict:
    """Triggers remote compilation of the project on Overleaf."""
    api = api or get_api()
    s = api._get_session()
    r = s.post(
        f"{HOST}/project/{project_id}/compile?enable_pdf_caching=true",
        json={"rootDoc_id": None, "draft": False, "check": "silent",
              "incrementalCompilesEnabled": False},
        headers={"x-csrf-token": api._get_csrf_token(project_id),
                 "Referer": f"{HOST}/project/{project_id}"},
    )
    r.raise_for_status()
    return r.json()


def download_pdf(res: dict, out_dir: str = "out") -> str:
    """Downloads the compiled PDF from Overleaf storage."""
    os.makedirs(out_dir, exist_ok=True)
    pdf = next(f for f in res.get("outputFiles", []) if f.get("path") == "output.pdf")
    base = res.get("pdfDownloadDomain", "https://compiles.overleafusercontent.com")
    params = {
        "compileGroup": res.get("compileGroup", "standard"),
        "clsiserverid": res.get("clsiServerId"),
        "enable_pdf_caching": "true",
    }
    r = requests.get(base + pdf["url"], params=params)
    r.raise_for_status()

    tmp = os.path.join(out_dir, "output.pdf")
    with open(tmp, "wb") as f:
        f.write(r.content)
    return tmp


def rename_pdf(tmp_path: str, role: str, candidate_name: str = None) -> str:
    """Renames the downloaded PDF using the configured naming template."""
    raw_name = candidate_name or os.environ.get("CANDIDATE_NAME") or os.environ.get("USER_NAME") or os.environ.get("NAME") or "Candidate"
    name_prefix = re.sub(r"[^A-Za-z0-9]+", "_", raw_name).strip("_")
    slug = re.sub(r"[^A-Za-z0-9]+", "_", role).strip("_")

    # Format using template (default: {name}_Your_Next_{role}.pdf)
    template = os.environ.get("CV_NAMING_TEMPLATE", "{name}_Your_Next_{role}.pdf")
    filename = template.format(name=name_prefix, role=slug)
    if not filename.endswith(".pdf"):
        filename += ".pdf"

    # Optional length check if configured in .env (0 or unset = no restriction)
    max_len = int(os.environ.get("MAX_FILENAME_LENGTH", "0"))
    if max_len > 0 and len(filename) >= max_len:
        raise ValueError(
            f"Generated filename too long ({len(filename)} chars): '{filename}'. "
            f"Configured MAX_FILENAME_LENGTH is {max_len}."
        )

    final = os.path.join(os.path.dirname(tmp_path), filename)
    os.replace(tmp_path, final)
    return final


def generate_cv(
    role: str,
    latex_source: str = "cv.tex",
    project_id: str = None,
    candidate_name: str = None,
    out_dir: str = "out"
) -> str:
    """Compile and download CV PDF from Overleaf.

    Args:
        role: Target role slug (e.g. 'Agent_Dev', 'AI_Eng').
        latex_source: Either raw LaTeX string (from AI/LLM) or a path to a .tex file.
        project_id: Optional Overleaf project ID override. Defaults to OVERLEAF_PROJECT_ID from .env.
        candidate_name: Optional candidate name override. Defaults to CANDIDATE_NAME from .env.
        out_dir: Destination folder for the PDF.

    Returns:
        The final path to the generated PDF.
    """
    pid = project_id or os.environ.get("OVERLEAF_PROJECT_ID")
    if not pid:
        raise ValueError(
            "OVERLEAF_PROJECT_ID is missing. Please set it in your .env file or pass it as an argument."
        )

    api = get_api()
    upload_tex(pid, latex_source, api=api)
    res = compile_project(pid, api=api)
    if res.get("status") != "success":
        raise RuntimeError(f"Overleaf compilation failed: {res}")

    tmp = download_pdf(res, out_dir=out_dir)
    return rename_pdf(tmp, role, candidate_name=candidate_name)


def count_pdf_pages(pdf_path: str) -> int:
    """Returns the total number of pages in the generated PDF file."""
    try:
        from pypdf import PdfReader
        reader = PdfReader(pdf_path)
        return len(reader.pages)
    except Exception:
        try:
            with open(pdf_path, "rb") as f:
                content = f.read()
            return max(1, len(re.findall(rb"/Type\s*/Page\b", content)))
        except Exception:
            return 1


# ---------- CLI execution ----------
if __name__ == "__main__":
    role = sys.argv[1] if len(sys.argv) > 1 else input("Role slug (e.g. Agent_Dev): ")

    if len(sys.argv) > 2:
        source = sys.argv[2]
    elif not sys.stdin.isatty():
        source = sys.stdin.read()
    else:
        default_file = str(PROJECT_ROOT / "cv.tex")
        example_file = str(PROJECT_ROOT / "cv.example.tex")
        if os.path.exists(default_file):
            source = default_file
        elif os.path.exists(example_file):
            source = example_file
        else:
            source = input("LaTeX source (file path or text): ")

    final_path = generate_cv(role, source)
    pages = count_pdf_pages(final_path)
    print(f"saved: {final_path} ({pages} page{'s' if pages != 1 else ''})")
    if pages > 1:
        print(f"⚠️ Warning: The compiled PDF has {pages} pages! Consider tightening bullet points to fit on 1 page.")